# Generated by Django 2.1.15 on 2020-05-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_at',
            field=models.DateField(),
        ),
    ]
