# Generated by Django 2.1.15 on 2020-05-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_poll_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Vote',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='is_active',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='name',
            new_name='title',
        ),
    ]
